# Generated by Django 4.0.4 on 2022-04-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='photo',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
