# Generated by Django 4.0.4 on 2022-04-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_signup_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
